# Generated by Django 3.2 on 2023-01-10 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_rename_original_bag_order_original_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='diameter',
        ),
        migrations.RemoveField(
            model_name='orderlineitem',
            name='height',
        ),
        migrations.RemoveField(
            model_name='orderlineitem',
            name='opacity',
        ),
        migrations.RemoveField(
            model_name='orderlineitem',
            name='product_color',
        ),
        migrations.RemoveField(
            model_name='orderlineitem',
            name='width',
        ),
    ]
