# Generated by Django 3.2 on 2023-01-05 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='diameter',
            field=models.CharField(default='inside', max_length=255),
        ),
    ]
